#	Makefile 编写规则
#		[目标对象]:[依赖对象]
#		[制表符]如何通过依赖对象生成目标对象的编译命令
#
#	Makefile当中有几个预定义的变量
#	$@	代表要生成的对象
#	$^	代表所有的依赖对象
#	$<	代表所有依赖对象当中的第一个
#在Makefile中，永远只生成第一个对象，生成后则退出

all:test
test:test.c
	gcc test.c tmp.c -o test
.PHONY:clean
clean:
	rm -f test
